name: Selenium Test on Windows 10

on:
  push:
    branches: [ main ]
    paths-ignore:
      - "README.md"
  pull_request:
    branches: [ main ]


jobs:
  test:
    runs-on: windows-2019

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - uses: actions/setup-java@v3
      with:
        distribution: 'microsoft'
        java-version: '11'

    - name: Run tests
      run: |
        # Run your Selenium tests
        mvn clean test -Dtest=MainTest
