name: Selenium Test on Windows 10

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: windows-2019

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup JDK
      uses: actions/setup-java@v2
      with:
        java-version: '11'

    - name: Setup Chrome browser
      uses: actions/setup-chrome@v1
      with:
        chrome-version: 'latest'

    - name: Run tests
      run: |
        # Run your Selenium tests
        mvn test -Dtest=MainTest
