name: Selenium Test on Windows Server

on:
  push:
    branches: [ main ]
    paths-ignore:
      - "README.md"
  pull_request:
    branches: [ main ]


jobs:
  test:
    runs-on: macOS-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - uses: actions/setup-java@v3
      with:
        java-version: '11'
        java-package: 'jdk'
        architecture: 'x64'
        distribution: 'corretto'

    - name: Run tests
      run: |
        # Run your Selenium tests
        mvn clean test -Dtest=MainTest
